name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  buildx:
    runs-on: ubuntu-latest

    steps:
    - uses: docker/setup-buildx-action@v3
    - name: Set up Docker Buildx
      run: docker buildx create --use
      run: docker buildx build --platform=linux/amd64,linux/arm64 -f "Dockerfile" --push -t ajmezza9/dsldev:latest "."
